runtime: Java11
entrypoint: 'java -jar google-appengine-standard-1.0-SNAPSHOT-all.jar'
instance_class: F2
env: flex
automatic_scaling:
  max_num_instances: 1

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto


