runtime: java11
entrypoint: 'com.pandey.shubham.tictalk-1.2-SNAPSHOT-all.jar'
instance_class: F1
inbound_services:
  - warmup

automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
