runtime: java11
#entrypoint: 'build/libs/com.pandey.shubham.tictalk-1.1-SNAPSHOT-all.jar'
instance_class: F1

inbound_services:
  - warmup
automatic_scaling:
  min_idle_instances: 0
  min_instances: 0
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  CLOUD_SQL_USERNAME: admin-shubham
  CLOUD_SQL_PASSWORD: tictalk@db5678
  CLOUD_SQL_DATABASE_NAME: tictalk
  CLOUD_SQL_CONNECTION_NAME: tictalk-app:asia-south2:tictalk-app-prod