runtime: java11
instance_class: F2
handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    secure: optional
    redirect_http_response_code: 301
    script: auto

error_handlers:
  - error_code: timeout
  - file: index.html

inbound_services:
  - warmup

service:
  - default

basic_scaling:
  max_instances: 1
  idle_timeout: 1m